#!/bin/bash

# Input check
if [[ -z ${1+x} ]]; then
  echo "This script requires the name of the app folder you are trying to install"
fi
if [[ ! -d "apps/$1" ]]; then
  echo "apps/$1 does not exist please create an app folder for this app"
fi
if [ "$EUID" -eq 0 ]; then 
  echo "Do not run this script as root, instead make your user a member of the 'docker' group"
  echo "sudo usermod -aG docker \$USER"
  exit 1
fi

# Build folder and env setup
cd apps/$1

# Build image
echo "building image"
docker build --build-arg REPO=local/proot-apps -t local-$1 .

# Extract FS and add to install folder
echo "extracting fs"
rm -Rf $HOME/proot-apps/{ghcr.io_local_proot-apps_$1,tmp}
mkdir -p $HOME/proot-apps/{ghcr.io_local_proot-apps_$1,tmp}
cd $HOME/proot-apps/tmp
docker save local-$1 > image.tar
tar xf image.tar
tar -xf $(ls -S blobs/sha256/* | head -1) -C $HOME/proot-apps/ghcr.io_local_proot-apps_$1
cd ..
rm -Rf tmp/


echo "$1 installed as ghcr.io/local/proot-apps:$1"
printf "\nTo install: \nproot-apps install ghcr.io/local/proot-apps:$1\n"
