#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/256x256/apps/spotify-client.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/spotify-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/spotify-pa.desktop
